# Generated by Django 3.0.3 on 2020-03-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('history', models.TextField(max_length=3000, verbose_name='История проекта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000, verbose_name='Задача')),
                ('complated', models.BooleanField(verbose_name='Метка о выполнении')),
                ('project_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(max_length=250, verbose_name='Ссылка на сайт')),
                ('domain_d', models.TextField(max_length=1000, verbose_name='Доступы к регистратору')),
                ('server_d', models.TextField(max_length=1000, verbose_name='Доступ к серверу')),
                ('bd_d', models.TextField(max_length=1000, verbose_name='Доступ к базе')),
                ('admin_panel', models.TextField(max_length=1000, verbose_name='Админка')),
                ('main_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Project', verbose_name='Проект')),
            ],
        ),
    ]
