# Generated by Django 3.0.3 on 2020-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200302_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='project',
            name='history',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='История проекта'),
        ),
        migrations.AlterField(
            model_name='site',
            name='admin_panel',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Админка'),
        ),
        migrations.AlterField(
            model_name='site',
            name='bd_d',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Доступ к базе'),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain_d',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Доступы к регистратору'),
        ),
        migrations.AlterField(
            model_name='site',
            name='server_d',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Доступ к серверу'),
        ),
    ]
