# Generated by Django 3.0.3 on 2020-03-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20200302_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='main_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sites.Project', verbose_name='Проект'),
        ),
    ]
