# Generated by Django 3.0.3 on 2020-03-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='sites.Clients', verbose_name='Клиент'),
        ),
    ]
