# Generated by Django 3.0.3 on 2020-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_project_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('В ожидании обратной связи', 'В ожидании обратной связи'), ('Выполненно', 'Выполненно'), ('На доработке', 'На доработке'), ('Срочно', 'Срочно')], max_length=200, null=True),
        ),
    ]
