# Generated by Django 3.0.3 on 2020-03-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_clients_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='sites.Site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='sites.Clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='sites.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='project_todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Project', verbose_name='Проект'),
        ),
    ]
