# Generated by Django 3.0.3 on 2020-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20200303_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание задачи'),
        ),
    ]
