# Generated by Django 3.0.3 on 2020-03-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_site_clients_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='clients_site',
        ),
    ]
