# Generated by Django 3.0.3 on 2020-03-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_todostatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todostatus',
            options={'verbose_name': 'Статусы задач', 'verbose_name_plural': 'Статусы задач'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.TodoStatus', verbose_name='Статус'),
        ),
    ]
