# Generated by Django 3.0.3 on 2020-03-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_auto_20200318_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.DeleteModel(
            name='TodoStatus',
        ),
    ]
