# Generated by Django 3.0.3 on 2020-03-18 19:41

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_auto_20200318_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name': 'Статусы задач',
                'verbose_name_plural': 'Статусы задач',
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Status', verbose_name='Статус'),
        ),
    ]
